[package]
name = "smooth-wordings"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
clap = { version = "4.5.16", features = [ "derive" ]}
futures = "0.3.30"
log = "0.4.22"
ratatui = "0.28.0"
russh = "0.45.0"
simple_logger = "5.0.0"
tokio = "1.39.3"
